services:
  - type: web
    name: threat-incident-management-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
